// 타입 만들기
const types = {
  FETCH_SYMBOL_PROFILES: 'FETCH_SYMBOL_PROFILES',
  FETCH_SYMBOL_PROFILES_SUCCESS: 'FETCH_SYMBOL_PROFILES_SUCCESS',
  FETCH_SYMBOL_PROFILES_FAILURE: 'FETCH_SYMBOL_PROFILES_FAILURE',
  IS_FETCHING_COMPLETE: 'IS_FETCHING_COMPLETE',
};

export default types;
